# Generated by Django 4.2.16 on 2024-12-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='registration',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default='Eren', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=15, null=True),
        ),
    ]
