# Generated by Django 4.2.16 on 2024-12-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registration_email_registration_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
    ]
