# Generated by Django 4.2.16 on 2024-12-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_waitinglist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitinglist',
            unique_together={('email', 'event')},
        ),
    ]
