# Generated by Django 4.2.16 on 2024-12-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_waitinglist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitinglist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registered_at',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='attending',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='user',
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='message',
            field=models.TextField(blank=True, default='No message provided', null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='events.event'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='waiting', max_length=20),
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='date_joined',
        ),
    ]
