# Generated by Django 4.2.16 on 2024-12-14 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_waitinglist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registered_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
