# Generated by Django 4.2.17 on 2024-12-14 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_waitinglist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
