# Generated by Django 4.2.16 on 2024-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_event_user_alter_registration_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
