# Generated by Django 4.2.16 on 2024-12-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_registration_status_alter_waitinglist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting for Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting for Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='waiting', max_length=20),
        ),
    ]
