# Generated by Django 4.2.16 on 2024-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0030_alter_vendor_options_alter_vendor_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='vendor_groups', to='auth.group'),
        ),
    ]
