# Generated by Django 4.2.16 on 2024-12-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_vendor_options_alter_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
