# Generated by Django 4.2.16 on 2025-02-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0036_alter_vendor_groups_alter_vendor_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='vendor_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='vendor_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
