# Generated by Django 4.2.20 on 2025-04-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
