# Generated by Django 4.2.20 on 2025-04-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_alter_vendor_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vendor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='username',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
