# Generated by Django 4.2.20 on 2025-04-24 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='events.event'),
            preserve_default=False,
        ),
    ]
