# Generated by Django 4.2.20 on 2025-04-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_alter_category_options_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('completed', 'Payment Completed')], default='pending', max_length=20),
        ),
    ]
