# Generated by Django 4.2.20 on 2025-04-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_message_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Beverages'), ('merchandise', 'Merchandise'), ('tickets', 'Tickets & Passes'), ('services', 'Services'), ('other', 'Other')], max_length=255),
        ),
    ]
