# Generated by Django 4.2.20 on 2025-04-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Drinks', 'Drinks'), ('Clothing', 'Clothing'), ('Art', 'Art'), ('Merchandise', 'Merchandise'), ('Electronics', 'Electronics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
