# Generated by Django 4.2.20 on 2025-04-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_alter_product_category_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='category',
        ),
    ]
